#!/bin/sh
#

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

export NVM_HOMEBREW="$(brew --prefix nvm)"
export NVM_AUTOLOAD=1

zstyle ':omz:plugins:nvm' autoload yes
# zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading
