#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
installers=$(find . -name install.sh)
for installer in $installers
do 
    echo "Installing: ${installer}"
    source "${installer}"
done
